### ISSUE TITLE
C# wrapper or  c# calling example？

### ISSUE THREAD

**Issue by nnn149** [not-matthias/obs-rs#2]
Hello, I love your work. But I wouldn't use rust. I see that your repository has a C# project, can you make a C# wrapper, or c# call this library example.

**Comment by krispybyte** [comment]
No

**Comment by rlewkowicz** [comment]
@nnn149 If you're still looking for something in c# https://github.com/robmikh/SimpleRecorder. Then you can combine that with https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/CameraOpenCV/shared/OpenCVBridge to bridge over to c++ for opencv. 

I'll say though if you're trying to do stuff in this space and you're not an ace dev, you're going to hit so many snags. The smallest barrier to entry is going to be c++ imo
