### ISSUE TITLE
I'd be interested in pairing on model training if you're interested

### ISSUE THREAD

**Issue by rlewkowicz** [not-matthias/obs-rs#3]
I came across this looking for methods to do dx11 screen cap. I don't know anything about rust, and I don't know that I have the bandwidth for that now. 

I use the desktop duplication api for now, and I'll switch to dx11 based on the linked obs repo, but the real time sink (one of them) is model training. Right now I use yolov5 serialized to a tensorrt engine. If you're also using yolov5 I would be interested in sharing models. 

It takes a lot of time to even clip and annotate 1k images. I've got about 3k for d2 right now and a decent model. I'm trying to get that to 10k and I'd imagine you're in a similar boat for whatever you're targeting. 

If you're interested in discussing, maybe we can hop on discord or something.

**Comment by rlewkowicz** [comment]
I should add I think you'll find issues with that dx11 screen cap. Many games actually dont allow that hook. The winrt screen cap library for 1903 and above I think is what you want: https://github.com/obsproject/obs-studio/tree/master/libobs-winrt

It's my lowly opinion you'll hit quite the slog with this project if it's not one already. If you're going to wrap everything in rust, that's going to be kinda rough. The new opencv, 4.6 I think has better support for cuda mats. Ideally you could do this without ever leaving the graphics buffers. Idk if it's that simple with com objects.

**Comment by not-matthias** [comment]
Hey, feel free to send me a message: `not-matthias#1403`
