### ISSUE TITLE
Color breaks when checking images in C++ Opencv using FFI

### ISSUE THREAD

**Issue by KimYuwol** [not-matthias/obs-rs#8]
Can you add C++ example using FFI?
We succeeded in getting the data, but the color will be broken when we convert it to opencv Mat and check it.
This project will greatly contribute to my AI project.

**Comment by sirzechs753** [comment]
Hi, I also experiencing this issue with red V shooter games iykwim, did u happened to resolve this?

**Comment by nullmastermind** [comment]
+1 can you help me resolve
