### ISSUE TITLE
Issues with color after taking screenshots of VALORANT game screen

### ISSUE THREAD

**Issue by sonarent** [not-matthias/obs-rs#9]
![output](https://github.com/not-matthias/obs-rs/assets/115764121/6b5f50f8-6c22-494e-8749-edf264c90337)

Issue only occurs with VALORANT game, other games work. Any suggestions are welcome.

ty

**Comment by nullmastermind** [comment]
+1

**Comment by tanishqmanuja** [comment]
Since you closed it, did you find a fix ? .. i have the exact same issue.

**Comment by nullmastermind** [comment]
> Since you closed it, did you find a fix ? .. i have the exact same issue.

No. Unfortunately, this repository is not useful for Valorant. I don't think the author can resolve this issue.
